### ISSUE TITLE
Where can I get the gt_files for ScanNet while not ScanNet++ for evaluation?

### ISSUE THREAD

**Issue by laliwang** [PKU-EPIC/MaskClustering#1]
Thanks for your excellent works and generous sharing! Where I notice the data structure of ScanNet in your readme goes as follows:
data/scannet/processed

>   ├── scene0011_00
>       ├── pose                            <- folder with camera poses
>       │      ├── 0.txt 
>       │      ├── 10.txt 
>       │      └── ...  
>       ├── color                           <- folder with RGB images
>       │      ├── 0.jpg  (or .png/.jpeg)
>       │      ├── 10.jpg (or .png/.jpeg)
>       │      └── ...  
>       ├── depth                           <- folder with depth images
>       │      ├── 0.png  (or .jpg/.jpeg)
>       │      ├── 10.png (or .jpg/.jpeg)
>       │      └── ...  
>       ├── intrinsic                 
>       │      └── intrinsic_depth.txt       <- camera intrinsics
>       |      └── ...
>       └── scene0011_00_vh_clean_2.ply      <- point cloud of the scene
>   └── ...
  Since I cannot find any files in txt or npz format for evaluation in above path, I just wonder where I can download it? Thanks!

**Comment by MiYanDoris** [comment]
Sorry for the missing preprocessing script. I've added the script for preparing ScanNet200 ground truth here: preprocess/scannet/prepare_gt.py. It is a simplified version of the original ScanNet toolkit. You can follow the instruction in Readme.md to prepare them. Thanks for your feedback and feel free to contact with me.
