### ISSUE TITLE
How to improve 3D point cloud with missing labels?

### ISSUE THREAD

**Issue by YZsZY** [PKU-EPIC/MaskClustering#3]
Hello author, thanks for open source such an excellent job!  I've been working with the code recently, and I've noticed that some of the finer details (such as table legs, chair legs, etc.) are missing after 3D blending, even though the 2D Mask splits them up.
![image](https://github.com/PKU-EPIC/MaskClustering/assets/117158282/1925a550-20c4-47ca-b674-04c2fe1a8faa)

Could you give some suggestions about how to avoid missing these fine details(such as the config setting)? Thanks a lot!

**Comment by MiYanDoris** [comment]
Thank you for your feedback!
There is a quick way to address this issue: by decreasing the point_filter_threshold in the config. Following OVIR-3D, we employ a point filtering strategy in the filter_point function found in utils/post_process.py to remove points with a low detection ratio. Lowering the point_filter_threshold will retain more points, but please note that this may also increase noise. You will need to balance this trade-off accordingly.
