### ISSUE TITLE
About Training Time

### ISSUE THREAD

**Issue by AmingWu** [PKU-EPIC/MaskClustering#4]
Dear Authors,

Do you release the training code? How long does your method need to train?

**Comment by MiYanDoris** [comment]
Thank you for your interest!

As mentioned in our abstract, our model is training-free, allowing you to use our algorithm directly without any training process. As for the processing time of each scene, it typically costs 3-15 minutes. We have provided detailed statistics on this in our [README](https://github.com/PKU-EPIC/MaskClustering?tab=readme-ov-file#time-cost). Please refer to it for more information.
