### ISSUE TITLE
how to apply maskclustering into gaussian splatting

### ISSUE THREAD

**Issue by xuyanging** [PKU-EPIC/MaskClustering#6]
Hi,

 I saw the effect of putting the algorithm into 3dgs on your display page, I tried to reproduce it, but found that the mesh file of the scene needs to be imported in "vis_scene.py",(as follows) which is already available in scannet, but not in 3dgs. How do you handle this part

![image](https://github.com/user-attachments/assets/7bc13eb8-779b-4152-8d9b-dc4bcc0b8c9b)

**Comment by MiYanDoris** [comment]
Thank you for your question, and I apologize for the delayed response (just got back from vacation! 😊).

You're right that handling the 3D Gaussian scene is a bit different from working with point clouds. Here’s an overview of how I process the 3D Gaussian scene:

1. I store the center of each 3D Gaussian in a .ply file and treat them as a point cloud. You can load this with o3d.io.read_point_cloud.

2. If you’re planning to run a segmentation pipeline, here’s a rough outline:

    1. Establish the correspondence between 3D Gaussians and masks. My approach was fairly simple: for each pixel, I assign the Gaussian center with the highest volume density. The results are stored in a mask_dict following the ScanNet format:
        ```python
            mask_dict = {
                1: set(100, 2107, ...),
                2: set(298, 382, ...)
            }
        ```
    2. Write a dataset class to load the 3D Gaussian scene. Here's a sample dataset class:
        ```python
            class GaussianDataset:

                def __init__(self, seq_name) -> None:
                    'Store some meta information of the scene'
                
                def get_frame_list(self, stride):
                    'Return a list of frame IDs in this scene'
                
                def get_frame_mask_dict(self, frame_id):
                    '''Returns:
                        mask_dict: the mask_dict created earlier
                        frame_point_cloud_ids: IDs of points in this frame
                    '''
        ```
    3. For additional semantic segmentation, you’ll also need to implement these functions: get_label_features, get_frame_path, get_scene_points, and get_label_id.

    4. Finally, replace the frame_backprojection function in mask_backprojection.py with the get_frame_mask_dict method from your GaussianDataset class. That’s the only modification required.

I hope this helps! Let me know if you have further questions or need additional clarification.

**Comment by MiYanDoris** [comment]
Thank you for your interest in our work. As this is a toy example from our paper, we do not have a ready-to-share version of the code. Additionally, we’ve decided to keep this part of the project private. We appreciate your understanding.
